package learn.exception;

public class InnerThrow2 {

    public void tetst() {
        System.out.println("Throw2  test开始");

    }
}
